# Generated by Django 4.1.7 on 2023-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_alter_menu_options_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='getuserinfo',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
