# Generated by Django 4.1.7 on 2023-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_getuserinfo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getuserinfo',
            name='tel_num',
            field=models.CharField(max_length=12),
        ),
    ]
